projects/web-development/wdc-django-practice-3/django_practice_3/django_practice_3/urls.py
from django.contrib import admin
from django.urls import path

from artists import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artists/', views.artists, name='artists'),
    path('create-song/', views.create_song, name='create_song'),
    path('delete-song/', views.delete_song, name='delete_song'),
    path('create-artist/', views.create_artist, name='create_artist'),
    path('delete-artist/', views.delete_artist, name='delete_artist'),
    ##################
    # Your URLs here #
    ##################
]

projects/web-development/wdc-django-practice-3/django_practice_3/artists/models.py
from django.db import models


GENRE_CHOICES = (
    ("rock", "Rock"),
    ("pop", "Pop"),
)

class Artist(models.Model):
    artistic_name = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    picture_url = models.URLField(blank=True)
    popularity = models.IntegerField(blank=True)
    genre = models.CharField(choices=GENRE_CHOICES, max_length=255, blank=True)


class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    album_name = models.CharField(max_length=255, blank=True)

projects/web-development/wdc-django-practice-3/django_practice_3/artists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound

from .models import Artist, Song


def artists(request):
    artists = Artist.objects.all()
    return render(request, 'index.html', context={'artists': artists})


def create_song(request):
    artist_id = request.POST['artist_id']
    title = request.POST['title']
    album_name = request.POST.get('album_name', '')

    # validate required fields
    if not artist_id or not title:
        return redirect('artists')

    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        return HttpResponseNotFound()

    Song.objects.create(artist=artist, title=title, album_name=album_name)
    return redirect('artists')


def delete_song(request):
    song_id = request.POST['song_id']
    try:
        song = Song.objects.get(id=song_id)
    except Artist.DoesNotExist:
        return HttpResponseNotFound()
    song.delete()
    return redirect('artists')


def create_artist(request):
    artistic_name = request.POST['artistic_name']
    first_name = request.POST.get('first_name', '')
    last_name = request.POST.get('last_name', '')
    picture_url = request.POST.get('picture_url', '')
    popularity = request.POST.get('popularity', '')
    genre = request.POST.get('genre', '')
    
    if not artistic_name:
        return redirect('artists')
    
    Artist.objects.create(artistic_name=artistic_name, first_name=first_name,
    last_name=last_name, picture_url=picture_url, popularity=popularity,
    genre=genre)
    return redirect('artists')

def delete_artist(request):
    artist_id = request.POST['artist_id']
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        return HttpResponseNotFound()
    artist.delete()
    return redirect('artists')

projects/web-development/wdc-django-practice-3/django_practice_3/templates/index.html
<!doctype html>
<html lang="en" data-framework="jquery">
<head>
  <style media="screen">
    .completed{
      text-decoration: line-through;
    }
    form.inline{
      display: inline;
    }
  </style>
</head>
<body>
  <!-- Create Song form -->
  <h3>Add a new Song</h3>
  <form action="{% url 'create_song' %}" method='POST'>
    {% csrf_token %}
    <div>
      Title: <input type="text" name='title'> *
    </div>
    <div>
      Album name: <input type="text" name='album_name'>
    </div>
    <div>
      Artist:
      <select name='artist_id'>
        {% for artist in artists %}
          <option value="{{artist.id}}">{{artist.artistic_name}}</option>
        {% endfor %}
      </select> *
    </div>
    <br>
    <div>
        <i>Note: inputs with "*" symbol are required.</i>
    </div>
    <input type="submit" value="Add Song">
  </form>
  <hr>

  <!-- Create Artist form -->
  <h3>Add a new Artist</h3>
  <form action="{% url 'create_artist' %}" method='POST'> <!--  Add propper URL in form's action -->
    {% csrf_token %}
    <!-- Add here the fields for the 'Add Artist' form -->
    <div>
      Artistic name: <input type="text" name='artistic_name'> *
    </div>
    <div>
      First name: <input type="text" name='first_name'>
    </div>
    <div>
      Last name: <input type="text" name='last_name'>
    </div>
    <div>
      Picture url: <input type="url" name='picture_url'>
    </div>
    <div>
      Popularity: <input type="number" name='popularity' value=0>
    </div>
    <div>
      Genre: <input type="text" name='genre'>
    </div>
    <br>
    <div>
        <i>Note: inputs with "*" symbol are required.</i>
    </div>
    <div>
      <input type="submit" value="Add artist">
    </div>
  </form>
  <hr>

  <!-- List of Artists with their Songs -->
  <h1>List of Artists</h1>
  <ul>
    {% for artist in artists %}
      <li>
        <label>{{ artist.artistic_name }}</label>
        <!-- Form for deleting an Artist -->
        <form action="{% url 'delete_artist' %}" method='POST' class='inline'> <!--  Add propper URL in form's action -->
          {% csrf_token %}
          <!-- Add here the fields for the 'Delete Artist' form -->
          <input type="hidden" name="artist_id" value="{{artist.id}}">
          <input type="submit" name="delete_artist" value="Delete">
        </form>
        <ul>
          {% for song in artist.song_set.all %}
            <li>
              {{song.title}} (<i>Album: {{song.album_name}}</i>)
              <!-- Form for deleting a Song -->
              <form action="{% url 'delete_song' %}" method='POST' class='inline'>
                {% csrf_token %}
                <input type="hidden" name="song_id" value="{{ song.id }}">
                <input type="submit" name='delete_song' value='Delete'>
              </form>
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
</body>
</html>